services:
  future-train:
    build: .
    container_name: future-train
    restart: unless-stopped
    volumes:
      - ./checkpoints:/app/checkpoints
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
